### PR TITLE
Implement Categories Pick for fix #8

### LINKED ISSUE #8: Customize List Merchant by categories
AUTHOR
Berdasar dari https://github.com/ans-4175/random-gofood/issues/4#issuecomment-969912345
Issue ini menjadi bagian untuk Part III
Mengakomodir "Merchant List" berdasar kategori

===
ORIGINAL
you know sometimes in the group we want "I want X, I want Y, I want Z" how about we roll X Y Z ?

so it like randomize but the custom merchant, because we don't want to roll the "merchant W"

### PR DESCRIPTION
**Pull request by ans-4175**
I use radio from WiredRadio
put handler `onselected`, it works but facing some error render from React that I don't understand
image
Any idea @imballinst ?

This PR would close #8 by wiring through `fetchRandom` method in `merchant.js`.
Passing selected radio value, and listening from radio select event

### CODE REVIEW

**Comment by imballinst** [comment]
That's... interesting. Let me take a look... I think it's not a React error, it's something-something from Lit: https://lit.dev/docs/components/defining/.

`wired-elements-react` is just a very simple wrapper of `wired-elements`: https://github.com/rough-stuff/wired-elements-react/blob/main/src/WiredRadioGroup.ts --> https://github.com/rough-stuff/wired-elements/blob/master/src/wired-radio-group.ts.

I'll try in my local then try in CodeSandbox.

**Comment by imballinst** [comment]
Hmm, on a second thought, I think it's because of the wheel. If I remove the wheel, changing the radio groups won't make the UI crash. Something during the re-render causes the wheel to crash.

**Comment by imballinst** [comment]
@ans-4175 when changing the radio, `wheelData` somehow has this `<empty slot>` thing.

image

**Comment by imballinst** [comment]
Kalau `pickNRandom` diganti jadi ini, gimana?

```js
export function pickNRandom(arr, n) {
  // When `n` is more than or equal to the number of elements in `arr`, early return.
  if (n >= arr.length) {
    return arr;
  }
  
  // Create 2 arrays, 1 for result, 1 for the "source pool".
  const result = [];
  const source = [...arr];

  for (let i = 0; i < n; i++) {
    const idx = Math.floor(Math.random() * source.length);
    // By splicing here, we also ensure that elements in `result` will be unique,
    // since elements that are spliced won't be picked anymore.
    const [spliced] = source.splice(idx, 1);
    result.push(spliced);
  }
  
  return result;
}
```

Kayaknya sebelumnya ada bug yang menyebabkan dia nggak ngisi array elementnya. Saya ganti jadi ini aman sih hasilnya.

image

image

**Comment by ans-4175** [comment]
> Kalau pickNRandom diganti jadi ini, gimana?

Yes, it works like a charm.
Edited done, push.

**Pull request merged**
